#include "runtime/default_scene_json.hpp"

namespace studio_runtime
{
    std::string BuildDefaultSceneTemplateSceneJson()
    {
        return
            "{\n"
            "  \"version\": 1,\n"
            "  \"entities\": [\n"
            "    {\n"
            "      \"id\": 1000,\n"
            "      \"name\": \"OriginMarker\",\n"
            "      \"values\": {\n"
            "        \"transform\": {\n"
            "          \"position\": [0.0, 0.0, 0.0],\n"
            "          \"rotation\": [0.0, 0.0, 0.0],\n"
            "          \"scale\": [0.14, 0.14, 0.14]\n"
            "        }\n"
            "      },\n"
            "      \"overrides\": {},\n"
            "      \"object\": { \"kind\": \"Object\", \"selectable\": true },\n"
            "      \"renderable\": { \"mesh\": \"builtin:octahedron\", \"visible\": false, \"albedo\": [0.9, 0.9, 0.9] }\n"
            "    },\n"
            "    {\n"
            "      \"id\": 1010,\n"
            "      \"name\": \"Axis_X\",\n"
            "      \"values\": { \"transform\": { \"position\": [1.0, 0.0, 0.0], \"rotation\": [0.0, 0.0, 0.0], \"scale\": [2.0, 0.03, 0.03] } },\n"
            "      \"overrides\": {},\n"
            "      \"object\": { \"kind\": \"Object\", \"selectable\": true },\n"
            "      \"renderable\": { \"mesh\": \"builtin:cube\", \"visible\": false, \"albedo\": [0.914, 0.337, 0.337] }\n"
            "    },\n"
            "    {\n"
            "      \"id\": 1020,\n"
            "      \"name\": \"Axis_Y\",\n"
            "      \"values\": { \"transform\": { \"position\": [0.0, 1.0, 0.0], \"rotation\": [0.0, 0.0, 0.0], \"scale\": [0.03, 2.0, 0.03] } },\n"
            "      \"overrides\": {},\n"
            "      \"object\": { \"kind\": \"Object\", \"selectable\": true },\n"
            "      \"renderable\": { \"mesh\": \"builtin:cube\", \"visible\": false, \"albedo\": [0.439, 0.839, 0.455] }\n"
            "    },\n"
            "    {\n"
            "      \"id\": 1030,\n"
            "      \"name\": \"Axis_Z\",\n"
            "      \"values\": { \"transform\": { \"position\": [0.0, 0.0, 1.0], \"rotation\": [0.0, 0.0, 0.0], \"scale\": [0.03, 0.03, 2.0] } },\n"
            "      \"overrides\": {},\n"
            "      \"object\": { \"kind\": \"Object\", \"selectable\": true },\n"
            "      \"renderable\": { \"mesh\": \"builtin:cube\", \"visible\": false, \"albedo\": [0.369, 0.651, 0.961] }\n"
            "    },\n"
            "    {\n"
            "      \"id\": 2100,\n"
            "      \"name\": \"EditorCamera\",\n"
            "      \"values\": { \"transform\": { \"position\": [-4.0, 3.0, -6.0], \"rotation\": [0.0, 0.0, 0.0], \"scale\": [1.0, 1.0, 1.0] } },\n"
            "      \"overrides\": {},\n"
            "      \"object\": { \"kind\": \"Camera\", \"selectable\": true },\n"
            "      \"camera\": {\n"
            "        \"position\": [-4.0, 3.0, -6.0],\n"
            "        \"target\": [0.5, 0.4, 0.5],\n"
            "        \"useTarget\": true,\n"
            "        \"fov\": 60.0,\n"
            "        \"near\": 0.1,\n"
            "        \"far\": 500.0,\n"
            "        \"enabled\": true\n"
            "      }\n"
            "    },\n"
            "    {\n"
            "      \"id\": 2200,\n"
            "      \"name\": \"MainCamera\",\n"
            "      \"values\": { \"transform\": { \"position\": [4.8, 2.2, -5.2], \"rotation\": [0.0, 0.0, 0.0], \"scale\": [1.0, 1.0, 1.0] } },\n"
            "      \"overrides\": {},\n"
            "      \"object\": { \"kind\": \"Camera\", \"selectable\": true },\n"
            "      \"camera\": {\n"
            "        \"position\": [4.8, 2.2, -5.2],\n"
            "        \"target\": [0.75, 0.5, 0.75],\n"
            "        \"useTarget\": true,\n"
            "        \"fov\": 50.0,\n"
            "        \"near\": 0.1,\n"
            "        \"far\": 500.0,\n"
            "        \"enabled\": true\n"
            "      }\n"
            "    }\n"
            "  ]\n"
            "}\n";
    }
}
